connector_image: clickup-source
tests:
  connection:
    - config_path: 'secrets/config.json'
      status: 'succeed'
    - config_path: 'test_files/invalid_config.json'
      status: 'failed'
  discovery:
    - config_path: 'secrets/config.json'
  basic_read:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/full_configured_catalog.json'
      empty_streams: ['status_histories']
      expect_trace_message_on_failure: false
  full_refresh:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/full_configured_catalog.json'
      ignored_fields:
        status_histories: ['current_status', 'status_history']
        workspaces: ['members']
  incremental:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/incremental_configured_catalog.json'
      future_state_path: 'test_files/abnormal_state.json'
      cursor_paths:
        status_histories: ['900900062157', 'lastUpdatedDate']
        tasks: ['900900062157', 'lastUpdatedDate']
