connector_image: bitbucket-server-source
tests:
  connection:
    - config_path: 'secrets/config.json'
      status: 'succeed'
    - config_path: 'test_files/invalid_config.json'
      status: 'failed'
  discovery:
    - config_path: 'secrets/config.json'
  basic_read:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/full_configured_catalog.json'
      expect_trace_message_on_failure: false
  full_refresh:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/full_configured_catalog.json'
  incremental:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/incremental_configured_catalog.json'
      future_state_path: 'test_files/abnormal_state.json'
      cursor_paths:
        commits: ['PLAYG/repo1', 'lastCommitterTimestamp']
        pull_request_activities: ['PLAYG/repo1', 'lastUpdatedDate']
        pull_request_diffs: ['PLAYG/repo1', 'lastUpdatedDate']
        pull_requests: ['PLAYG/repo1', 'lastUpdatedDate']
