connector_image: bitbucket-source
tests:
  spec:
    bypass_reason: "Covered by unit test"
  connection:
    - config_path: 'secrets/config.json'
      status: 'succeed'
    - config_path: 'test_files/invalid_config.json'
      status: 'failed'
  discovery:
    - config_path: 'secrets/config.json'
  basic_read:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/full_configured_catalog.json'
      empty_streams:
        - bitbucket_branches
      expect_trace_message_on_failure: false
  full_refresh:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/full_configured_catalog.json'
  incremental:
    - config_path: 'secrets/config.json'
      configured_catalog_path: 'test_files/incremental_configured_catalog.json'
      future_state_path: 'test_files/abnormal_state.json'
      cursor_paths:
        commits: ['RomanKyrnis/geekhub2019', 'cutoff']
        issues: ['RomanKyrnis/geekhub2019', 'cutoff']
        pull_request_activities: ['RomanKyrnis/geekhub2019', 'cutoff']
        pull_requests: ['RomanKyrnis/geekhub2019', 'cutoff']
